### ISSUE TITLE
Can't create wallet

### ISSUE THREAD

**Issue by TheTrunk** [TheTrunk/bitcore-wallet-hush#1]
Running  `./wallet create 'my wallet' 2-2` throws not a function error with lodash module in [bitcore-wallet-client-hush](https://github.com/TheTrunk/bitcore-wallet-client-hush) module. 

How to setup everything guide: https://gist.github.com/TheTrunk/935000778625101109bd9923f568e50e

Bounty: 10HUSH for fixing everything - Wallet creation and transactions working on mainnet.

**Comment by TheTrunk** [comment]
I think it is a problem with bitcore-lib-hush being outdated as I have tested it with original bitcore stuff but pointing it to bitcore-lib-hush and recieved the same error.

**Comment by TheTrunk** [comment]
Its not a problem of bitcore-lib-hush. Its definitly a problem of bitcore-wallet-client-hush.

**Comment by alihaghani** [comment]
Running `./wallet create 'my wallet' 2-2` for the first time after following the setup guide linked here, getting the following. Is the BWC client cloned in the guide not the latest version?

`$ ./wallet create 'my wallet' 2-2
Error: UPGRADE_NEEDED: BWC clients < 1.2 are no longer supported.
    at Function.API._parseError (/Users/alihaghani/Documents/GitHub/Hush/bitcore-wallet-hush/node_modules/bitcore-wallet-client-hush/lib/api.js:257:13)
    at /Users/alihaghani/Documents/GitHub/Hush/bitcore-wallet-hush/node_modules/bitcore-wallet-client-hush/lib/api.js:850:21
    at Request.callback (/Users/alihaghani/Documents/GitHub/Hush/bitcore-wallet-hush/node_modules/superagent/lib/node/index.js:718:3)
    at parser (/Users/alihaghani/Documents/GitHub/Hush/bitcore-wallet-hush/node_modules/superagent/lib/node/index.js:906:18)
    at IncomingMessage.res.on (/Users/alihaghani/Documents/GitHub/Hush/bitcore-wallet-hush/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`
